apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker-elk_kibana 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
          name: http
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-lb
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30924
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
