apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker-elk_logstash 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5044
          name: filebeat
        - containerPort: 9600
          name: monitoring
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 512Mi
        env:
          - name: ES_JAVA_OPTS
            value: -Xms256m -Xmx256m
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/config/
        - name: pipeline-config
          mountPath: /usr/share/logstash/pipeline/
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
#          items:
#          - key: logstash.yml
      - name: pipeline-config
        configMap:
          name: pipeline-config
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - port: 5044
    name: filebeat
  - port: 9600
    name: monitoring
